# -*- coding: utf-8 -*-
"""Telegram Bot (Launcher)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jp9YdPf5czbAb8eQenzsGY7oGJcL1UCw
"""

# -*- coding: utf-8 -*-

import logging
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup, WebAppInfo
from telegram.ext import Application, CommandHandler, ContextTypes

# --- Конфигурация ---
# ЗАМЕНИТЕ ЭТОТ ТОКЕН НА ВАШ ТОКЕН, ПОЛУЧЕННЫЙ ОТ @BotFather
TELEGRAM_TOKEN = "8414423840:AAGTmBCeORnBl9YVWpG6rOOrMq7L0Bafcqc"
# ЗАМЕНИТЕ ЭТУ ССЫЛКУ НА URL ВАШЕГО РАЗМЕЩЕННОГО МИНИ-ПРИЛОЖЕНИЯ
MINI_APP_URL = "https://joanseamrexgage-ui.github.io/atmosmenu/mini_app.html"

# --- Логирование ---
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)
logger = logging.getLogger(__name__)

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Отправляет приветственное сообщение с кнопкой для открытия Mini App."""
    user = update.effective_user

    # Создаем кнопку, которая открывает веб-приложение
    keyboard = [
        [InlineKeyboardButton("📖 Открыть кулинарную книгу", web_app=WebAppInfo(url=MINI_APP_URL))]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)

    await update.message.reply_text(
        f"Привет, {user.first_name}!\n\n"
        "Нажмите кнопку ниже, чтобы открыть интерактивную кулинарную книгу.",
        reply_markup=reply_markup
    )

def main() -> None:
    """Запускает бота."""
    if "ВАШ_ТЕЛЕГРАМ_ТОКЕН" in TELEGRAM_TOKEN:
        print("Ошибка: Пожалуйста, замените токен в файле telegram_bot.py.")
        return
    if "https---your" in MINI_APP_URL:
        print("Внимание: Не забудьте указать URL вашего мини-приложения в файле telegram_bot.py.")

    application = Application.builder().token(TELEGRAM_TOKEN).build()
    application.add_handler(CommandHandler("start", start))

    print("Бот-лаунчер запускается...")
    application.run_polling()

if __name__ == "__main__":
    main()